services:
  dload:
    container_name: dload
    image: fuzzknob/dload
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/raid1/shared/dload/config:/config
      - /mnt/raid1/shared/dload/downloads:/downloads
    ports:
      - "8082:80"
    restart: unless-stopped

  myspeed:
    container_name: MySpeed
    image: germannewsmaker/myspeed
    ports:
      - "5216:5216"
    volumes:
      - /mnt/raid1/shared/myspeed/data:/myspeed/data
    restart: unless-stopped

  metube:
    container_name: metube
    image: ghcr.io/alexta69/metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - /mnt/raid1/shared/metube:/downloads

  cloud-torrent:
    image: boypt/cloud-torrent
    container_name: cloud-torrent
    ports:
      - "3000:3000"
    volumes:
      - /mnt/raid1/shared/downloads:/downloads
      - /mnt/raid1/shared/torrents:/torrents
    restart: unless-stopped
              
  stirling-pdf:
      image: frooodle/s-pdf:latest
      ports:
        - '2001:8080'
      volumes:
        - /mnt/raid1/shared/dockerpdf/trainingData:/usr/share/tessdata
        - /mnt/raid1/shared/dockerpdf/extraConfigs:/configs
        - /mnt/raid1/shared/dockerpdf/customFiles:/customFiles/
        - /mnt/raid1/shared/dockerpdf/logs:/logs/
      environment:
        - DOCKER_ENABLE_SECURITY=false
        - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
        - LANGS=pt_GB
  
